version: '3.8'

services:
  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: tripplanner
      POSTGRES_PASSWORD: root
      TZ: UTC
    volumes:
      - tripplanner-pg-local:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  tripplanner-pg-local: